# Generated by Django 4.2.3 on 2023-07-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
